# Publish pipelines are triggered via HTTP method in release pipeline. See v3 publish
stages:
- stage: Linux_Images
  jobs:
  - job: Publish_all
    pool: 
      vmImage: 'Ubuntu-latest'
    steps:
    - bash: |
        echo $pswd | docker login -u $(dockerUsername) --password-stdin azurefunctions.azurecr.io
      displayName: login
      continueOnError: false
      env:
        pswd: $(dockerPassword)

    - bash: |
        set -e
        SOURCE_REGISTRY=azurefunctions.azurecr.io/azure-functions/3.0
        TARGET_REGISTRY=azurefunctions.azurecr.io/public/azure-functions

        if [ -z "$(TargetVersion)" ]; then
          echo "ERROR: TargetVersion is required"
          exit 1
        fi

        if [ -z "$(PrivateVersion)" ]; then
          echo "ERROR: PrivateVersion is required"
          exit 1
        fi

        echo "##vso[task.setvariable variable=SOURCE_REGISTRY]$SOURCE_REGISTRY"
        echo "##vso[task.setvariable variable=TARGET_REGISTRY]$TARGET_REGISTRY"
      displayName: set env
      continueOnError: false

    - bash: |
        set -e

        docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java8.1-appservice
        docker pull $SOURCE_REGISTRY/java:$(PrivateVersion)-java11.1-appservice

        docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java8.1-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java8.1-appservice
        docker tag $SOURCE_REGISTRY/java:$(PrivateVersion)-java11.1-appservice $TARGET_REGISTRY/java:$(TargetVersion)-java11.1-appservice

        docker push $TARGET_REGISTRY/java:$(TargetVersion)-java8.1-appservice
        docker push $TARGET_REGISTRY/java:$(TargetVersion)-java11.1-appservice

        docker system prune -a -f
      displayName: tag and push java images
      continueOnError: false


